---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmrs
  namespace: openmrs-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openmrs
  template:
    metadata:
      labels:
        env1: dev
        app: openmrs
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: openmrs
        image: snaidu/openmrs:1
        imagePullPolicy: "Always"
        ports:
          - containerPort: 8080
            protocol: TCP
